#!/usr/bin/perl

use v5.10;
use strict;
use warnings;
use Getopt::Std;

my @asnum = (
    'AS47541', # VKONTAKTE-SPB-AS
    'AS47764', # mailru-as
    'AS13238', # Yandex
    'AS43247', # YAMONEY-AS
    'AS197068', # QRATOR (drweb.ru)
    'AS200107'  # KL-EXT (kaspersky.ru)
);
my ($rr_rt, %ipnet) = "";

foreach my $asnet (@asnum) {
    my $rt_rn = getRTRejectNetworks($asnet);
    map {
	my (undef, undef, undef, undef, $net) = split(" ");
	print $net;
    } split("\n", $rt_rn);
    $rr_rt .= $rt_rn;
}
$rr_rt = join("\n",sort(split("\n",$rr_rt)));
print $rr_rt;

exit;

sub getRTRejectNetworks {
    my $as = shift if @_;
    return "" unless $as;
    my $ret;
    open (RT, 'echo "@rtconfig printPrefixRanges \"set routing-options static route %p/%m reject\n\" filter '.$as.'" | rtconfig -protocol ripe -config junos |') || die "Failed run rtconfig: $!\n";
    while (<RT>) {
        s/^\s*//;
        next unless /^set\s+/;
        $ret .= $_;
    }
    close RT;
    return $ret;
}
