#!/bin/sh

D="auto.ru|drweb.ru|imgsmail.ru|kaspersky.ru|kinopoisk.ru|mail.ru|odnoklasniki.ru|odnoklasniki.ua|odnoklassniki.ru|odnoklassniki.ua|ok.ru|ok.ua|vk.com|yandexdatafactory.com|yandex.ru|yandex.ua|ya.ru"

#( for D in $( echo ${D} | tr \| \  ); do echo ${D}; done ) | sed "s,.*\.\([^.]*\.[^.]*\)$,\1," | sort -u | awk '{ printf("%s|",$1); }'
#exit

D=$( echo ${D} | sed "s,\.,\\\.,g" )

cat /var/log/named/query.log* | awk '{ print $8 }' | sort -u | awk '/(^|\.)('${D}'|(yandex|drweb|kaspersky)\.[^.]+)$/'
sudo rm /var/log/named/query.log.* 2> /dev/null
sudo cp /dev/null /var/log/named/query.log
